on: [push]

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: List joss directory contents for debugging
        run: ls -l joss/

      - name: Build Draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: joss/paper.md

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v1
        with:
          name: joss
          path: joss/paper.pdf
